name: Build

on:
  workflow_dispatch:
    inputs:
      artifact:
        type: boolean
        description: "Store the artifact"
        required: false
  workflow_call:
    inputs:
      artifact:
        type: boolean
        description: "Store the artifact"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "22"
          cache: "maven"

      - name: Build with Maven
        run: mvn -B package --file pom.xml
