name: Publish documentation
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["apps/docs/**"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - id: cache
        uses: actions/cache@v4
        with:
          path: "**/node_modules/**"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        if: steps.cache.outputs.cache-hit != 'true'

      - uses: actions/configure-pages@v4

      - name: Build documentation
        run: npx turbo run build --filter=docs

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./apps/docs/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy documentation
        id: deployment
        uses: actions/deploy-pages@v4
